<?php
/**
 * @file
 * Openlayers Custom Controls
 */

/**
 * Implements hook_ctools_plugin_api()
 */
function openlayers_customcontrols_ctools_plugin_api($module, $api) {
  $path = drupal_get_path('module', 'openlayers_customcontrols') . '/includes';
  return array(
    'version' => 1,
    'path' => $path,
  );
}

function openlayers_customcontrols($form, &$form_state, $map_arg = NULL) {
	$path = drupal_get_path('module','openlayers_customcontrol');
	
	$form['#attach']['customcontrolpath'] = array(
		'#path' => $path,
	);
	return $form;
}

function openlayers_customcontrols_init()
{
//    drupal_add_js(drupal_get_path('module','openlayers').'/modules/openlayers_customcontrol/src/Plugin/Control/Treeview/js/object-observe-lite.js',
//        array( 'scope' => 'header', 'weight' => -10)
//    );
}